# Generated by Django 6.0.4 on 2026-04-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_friend_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
