# Generated by Django 6.0.4 on 2026-04-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_isbanned_alter_message_receiver_and_more'),
        ('myapp', '0004_friend_friendrequest'),
    ]

    operations = [
    ]
