# Generated by Django 6.0.4 on 2026-04-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20260414_1411'),
        ('myapp', '0005_user_isbanned_alter_user_profileimage'),
    ]

    operations = [
    ]
